#!/bin/bash
# PreToolUse hook for Claude Code and Codex: generated files are rebuilt by
# composer build, the release generator, npm run build-css-prod or
# agnostic-ai sync, so a hand edit is lost on the next build.
# Reads Claude's tool_input.file_path or the file headers of a Codex
# apply_patch, and denies with the JSON decision both tools accept.
set -euo pipefail

input="$(cat)"
tool_name="$(printf '%s' "$input" | jq -r '.tool_name // empty')"
file_path="$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty')"
patch="$(printf '%s' "$input" | jq -r '.tool_input.command // .tool_input.input // empty')"

deny() {
  printf '{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":%s}}\n' \
    "$(jq -Rn --arg s "$1" '$s')"
  exit 0
}

generated_reason() {
  local path="$1"
  [[ "$path" == /* ]] || path="/$path"
  case "$path" in
    */content/releases/_index.md) return 1 ;;
    */content/releases/*)
      echo "Release pages come from GitHub releases via build/generate-releases.php." ;;
    */content/documentation/reference/api/* | */static/api.json | */static/api_search.json)
      echo "The API reference comes from Phel docstrings via composer build (build/api-*.php)." ;;
    */content/documentation/reference/errors.md)
      echo "The error reference comes from build/src/ErrorReference/ via composer build." ;;
    */static/tailwind.css | */static/llms-full.txt | */static/agentic-coding.md)
      echo "Built by npm run build-css-prod from css/ and scripts/." ;;
    */CLAUDE.md | */AGENTS.md | */.claude/rules/* | */.claude/skills/* | */.claude/agents/* | */.claude/settings.json | */.claude/launch.json | */.codex/* | */.agents/skills/*)
      echo "Generated by agnostic-ai sync. Edit .agnostic-ai/ and run agnostic-ai sync." ;;
    *) return 1 ;;
  esac
}

check() {
  local reason
  if reason="$(generated_reason "$1")"; then
    deny "Generated file: $1. $reason"
  fi
}

[[ -n "$file_path" ]] && check "$file_path"

if [[ "$tool_name" == "apply_patch" && -n "$patch" ]]; then
  while IFS= read -r path; do
    check "$path"
  done < <(printf '%s\n' "$patch" | sed -nE 's/^\*\*\* (Add|Update|Delete) File: (.*)$/\2/p')
fi

exit 0
